# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-30 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cotegory',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='bbs',
            name='image',
            field=models.ImageField(blank=True, default='image/null.gif', upload_to='image/BBS'),
        ),
    ]
