# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-25 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20170823_1613'),
        ('bbs', '0004_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs',
            name='land',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='map.LandMessage'),
        ),
    ]
