# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-24 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(choices=[(1, '\u4e2a\u4f53\u7ecf\u8425\u6237'), (2, '\u5c0f\u578b\u519c\u573a'), (3, '\u5927\u578b\u79cd\u690d\u4e1a\u57fa\u5730'), (4, '\u4e2a\u4f53\u517b\u6b96\u4e1a'), (5, '\u5927\u578b\u517b\u6b96\u4e1a')], default=1, verbose_name='\u7528\u6237\u7c7b\u578b'),
        ),
    ]
