# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-08 22:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='\u6807\u9898')),
                ('content', models.CharField(max_length=1000)),
                ('view_count', models.IntegerField()),
                ('favorite_count', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='image/null.gif', upload_to='image/map')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u519c\u7530\u4fe1\u606f',
                'verbose_name_plural': '\u519c\u7530\u4fe1\u606f',
            },
        ),
    ]
