# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-10 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmessage',
            name='lan_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='landmessage',
            name='land_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='landmessage',
            name='land_x',
            field=models.FloatField(default=0),
        ),
    ]
