# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-10 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20170810_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmessage',
            name='lan_y',
        ),
        migrations.AddField(
            model_name='landmessage',
            name='land_y',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='landmessage',
            name='land_x',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
