# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-12 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20170810_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmessage',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='landmessage',
            name='search_id',
            field=models.IntegerField(default=0),
        ),
    ]
