# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-14 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20170812_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmessage',
            name='address',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
