# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-19 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_userfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50, verbose_name='\u7701\u4efd')),
                ('name', models.CharField(max_length=50, verbose_name='\u7701\u4efd\u540d')),
                ('price', models.FloatField(verbose_name='\u5e73\u5747\u4ef7\u683c')),
            ],
            options={
                'verbose_name': '\u5e73\u5747\u4ef7\u683c',
                'verbose_name_plural': '\u5e73\u5747\u4ef7\u683c',
            },
        ),
    ]
