# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-19 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(default=0, verbose_name='\u5e73\u5747\u4ef7\u683c'),
        ),
    ]
