# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-22 17:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0009_auto_20170819_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='landComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='\u8bc4\u8bba')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba',
                'verbose_name_plural': '\u8bc4\u8bba',
            },
        ),
        migrations.AddField(
            model_name='landmessage',
            name='emotion',
            field=models.IntegerField(default=0, verbose_name='\u60c5\u611f\u7cfb\u6570'),
        ),
        migrations.AddField(
            model_name='landcomment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.LandMessage', verbose_name='\u5730\u5757'),
        ),
    ]
