# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-23 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20170822_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmessage',
            name='phone',
            field=models.CharField(default=0, max_length=100, verbose_name='\u8054\u7cfb\u65b9\u5f0f'),
        ),
    ]
