# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-11 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_auto_20170826_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmessage',
            name='cover',
            field=models.IntegerField(default=0.1, verbose_name='\u914d\u9001\u8ddd\u79bb'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_image',
            field=models.ImageField(upload_to='image/map'),
        ),
    ]
